apiVersion: v1
kind: Service
metadata:
  labels:
    app: heyburrito
  name: heyburrito-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 3333
  selector:
    app: heyburrito
  type: ClusterIP
