apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .tuberAppName }}-mongodb
  name: {{ .tuberAppName }}-mongodb-service
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: {{ .tuberAppName }}-mongodb
  clusterIP: 10.62.134.134 # sorry, not sorry
  type: ClusterIP
