apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: heyburrito
spec:
  hosts:
  - {{.clusterDefaultHost}}
  - {{ .tuberAppName }}.{{.clusterDefaultHost}}
  gateways:
  - {{.clusterDefaultGateway}}
  http:
  - route:
    - destination:
        host: heyburrito-service
        port:
          number: 8080
