apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: heyburrito
spec:
  hosts:
  - {{.clusterDefaultHost}}
  gateways:
  - {{.clusterDefaultGateway}}
  http:
  - match:
    - uri:
        prefix: /{{.tuberAppName}}
    route:
    - destination:
        host: heyburrito-service
        port:
          number: 80
